name: publish-beta
on:
  workflow_dispatch:
  push:
    branches: [dev]
jobs:
  publish-to-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v3
      - name: Setting up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Grant permissions to Gradle
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew publishExtensions -Pcreds.ext.key='${{ secrets.EXTENSION_REPO_KEY }}' -Dorg.gradle.jvmargs=-Xmx512m --no-daemon